DROP TABLE IF EXISTS TBL_MOVIES;
 
CREATE TABLE TBL_MOVIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  year_release INT,
  description VARCHAR(250) NOT NULL,
  genre VARCHAR(250) DEFAULT NULL,
  active BIT NOT NULL 
);